from PyQt5 import QtCore, QtGui, QtWidgets
from StudentMainPage import Ui_StudentMainWindow
from TeacherMainPage import Ui_TeacherMainWindow
import sqlite3
import res

connection = sqlite3.connect("Users.db")
cursor = connection.cursor()
sqlCommand_student = "CREATE TABLE if NOT EXISTS tblStudentUsers(firstName TEXT,surname TEXT,username TEXT PRIMARY KEY,password TEXT, Logged_in INTEGER)"
sqlCommand_teacher = "CREATE TABLE if NOT EXISTS tblTeacherUsers(title TEXT,firstName TEXT,surname TEXT,username TEXT PRIMARY KEY,password TEXT, Logged_in INTEGER)"
cursor.execute(sqlCommand_student)
cursor.execute(sqlCommand_teacher)
connection.commit()
connection.close()

class Ui_WelcomePage(object):
    def setupUi(self, WelcomePage):
        WelcomePage.setObjectName("WelcomePage")
        WelcomePage.resize(1200, 800)
        WelcomePage.setWindowTitle("Calculus Revision Tool")
        self.centralwidget = QtWidgets.QWidget(WelcomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("QStackedWidget#stackedWidget{background-image: url(:/images/background.jpg);}")
        self.stackedWidget.setObjectName("stackedWidget")
#-----------------------------------------------------------------------Teacher Welcome Page
        self.teacherWelcomePage = QtWidgets.QWidget()
        self.teacherWelcomePage.setObjectName("teacherWelcomePage")
        self.registerButton = QtWidgets.QPushButton(self.teacherWelcomePage, clicked= lambda: self.gotoTeacherRegisterPage())
        self.registerButton.setGeometry(QtCore.QRect(450, 580, 300, 60))
        font.setPointSize(18)
        font.setBold(True)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("QPushButton#registerButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#registerButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#registerButton:pressed{background-color: rgb(170, 170, 170);}")
        self.registerButton.setText("Register")
        self.registerButton.setObjectName("registerButton")
        self.logInButton = QtWidgets.QPushButton(self.teacherWelcomePage, clicked= lambda: self.gotoTeacherLoginPage())
        self.logInButton.setGeometry(QtCore.QRect(450, 500, 300, 60))
        self.logInButton.setFont(font)
        self.logInButton.setStyleSheet("QPushButton#logInButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#logInButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#logInButton:pressed{background-color: rgb(170, 170, 170);}")
        self.logInButton.setText("Log In")
        self.logInButton.setObjectName("logInButton")
        self.toolLabel = QtWidgets.QLabel(self.teacherWelcomePage)
        self.toolLabel.setGeometry(QtCore.QRect(300, 200, 600, 100))
        font.setPointSize(30)
        self.toolLabel.setFont(font)
        self.toolLabel.setStyleSheet("color: rgb(255, 255, 255);background-color:rgb(0,0,0);border-radius:10px;")
        self.toolLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toolLabel.setText("Calculus Revision Tool")
        self.toolLabel.setObjectName("toolLabel")
        self.studentButton = QtWidgets.QPushButton(self.teacherWelcomePage, clicked= lambda: self.gotoStudent())
        self.studentButton.setGeometry(QtCore.QRect(0, 0, 200, 60))
        font.setPointSize(15)
        self.studentButton.setFont(font)
        self.studentButton.setStyleSheet("QPushButton#studentButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:5px;}\n"
"QPushButton#studentButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#studentButton:pressed{background-color: rgb(170, 170, 170);}")
        self.studentButton.setText("Student Login")
        self.studentButton.setObjectName("studentButton")
        self.teachersLabel = QtWidgets.QLabel(self.teacherWelcomePage)
        self.teachersLabel.setGeometry(QtCore.QRect(400, 270, 400, 100))
        font.setPointSize(25)
        self.teachersLabel.setFont(font)
        self.teachersLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.teachersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.teachersLabel.setText("For Teachers")
        self.teachersLabel.setObjectName("teachersLabel")
        self.stackedWidget.addWidget(self.teacherWelcomePage)
#-----------------------------------------------------------------------Student Welcome Page
        self.studentWelcomePage = QtWidgets.QWidget()
        self.studentWelcomePage.setObjectName("studentWelcomePage")
        self.teacherButton = QtWidgets.QPushButton(self.studentWelcomePage, clicked= lambda: self.gotoTeacher())
        self.teacherButton.setGeometry(QtCore.QRect(0, 0, 200, 60))
        font.setPointSize(15)
        self.teacherButton.setFont(font)
        self.teacherButton.setStyleSheet("QPushButton#teacherButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:5px;}\n"
"QPushButton#teacherButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#teacherButton:pressed{background-color: rgb(170, 170, 170);}")
        self.teacherButton.setText("Teacher Login")
        self.teacherButton.setObjectName("teacherButton")
        self.toolLabel_2 = QtWidgets.QLabel(self.studentWelcomePage)
        self.toolLabel_2.setGeometry(QtCore.QRect(300, 200, 600, 100))
        font.setPointSize(30)
        self.toolLabel_2.setFont(font)
        self.toolLabel_2.setStyleSheet("color: rgb(255, 255, 255);background-color:rgb(0,0,0);border-radius:10px;")
        self.toolLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.toolLabel_2.setText("Calculus Revision Tool")
        self.toolLabel_2.setObjectName("toolLabel_2")
        self.logInButton_2 = QtWidgets.QPushButton(self.studentWelcomePage, clicked= lambda: self.gotoStudentLoginPage())
        self.logInButton_2.setGeometry(QtCore.QRect(450, 500, 300, 60))
        font.setPointSize(18)
        self.logInButton_2.setFont(font)
        self.logInButton_2.setStyleSheet("QPushButton#logInButton_2{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#logInButton_2:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#logInButton_2:pressed{background-color: rgb(170, 170, 170);}")
        self.logInButton_2.setText("Log In")
        self.logInButton_2.setObjectName("logInButton_2")
        self.registerButton_2 = QtWidgets.QPushButton(self.studentWelcomePage, clicked= lambda: self.gotoStudentRegisterPage())
        self.registerButton_2.setGeometry(QtCore.QRect(450, 580, 300, 60))
        self.registerButton_2.setFont(font)
        self.registerButton_2.setStyleSheet("QPushButton#registerButton_2{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#registerButton_2:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#registerButton_2:pressed{background-color: rgb(170, 170, 170);}")
        self.registerButton_2.setText("Register")
        self.registerButton_2.setObjectName("registerButton_2")
        self.studentsLabel = QtWidgets.QLabel(self.studentWelcomePage)
        self.studentsLabel.setGeometry(QtCore.QRect(400, 270, 400, 100))
        font.setPointSize(25)
        self.studentsLabel.setFont(font)
        self.studentsLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.studentsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentsLabel.setText("For Students")
        self.studentsLabel.setObjectName("studentsLabel")
        self.stackedWidget.addWidget(self.studentWelcomePage)
#-----------------------------------------------------------------------Student Login Page
        self.studentLoginPage = QtWidgets.QWidget()
        self.studentLoginPage.setObjectName("studentLoginPage")
        self.StudentLoginLabel = QtWidgets.QLabel(self.studentLoginPage)
        self.StudentLoginLabel.setGeometry(QtCore.QRect(400, 125, 400, 100))
        font.setPointSize(30)
        self.StudentLoginLabel.setFont(font)
        self.StudentLoginLabel.setStyleSheet("color: rgb(255, 255, 255);background-color:rgb(0,0,0);border-radius:10px;")
        self.StudentLoginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StudentLoginLabel.setText("Student Login")
        self.StudentLoginLabel.setObjectName("StudentLoginLabel")
        self.StudentLoginButton = QtWidgets.QPushButton(self.studentLoginPage, clicked= lambda: self.student_login())
        self.StudentLoginButton.setGeometry(QtCore.QRect(450, 525, 300, 60))
        font.setPointSize(20)
        self.StudentLoginButton.setFont(font)
        self.StudentLoginButton.setStyleSheet("QPushButton#StudentLoginButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#StudentLoginButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#StudentLoginButton:pressed{background-color: rgb(170, 170, 170);}")
        self.StudentLoginButton.setText("Log In")
        self.StudentLoginButton.setObjectName("StudentLoginButton")
        self.StudentUsernameLineEdit = QtWidgets.QLineEdit(self.studentLoginPage)
        self.StudentUsernameLineEdit.setGeometry(QtCore.QRect(450, 300, 300, 50))
        font.setBold(False)
        font.setPointSize(15)
        self.StudentUsernameLineEdit.setFont(font)
        self.StudentUsernameLineEdit.setStyleSheet("QLineEdit#StudentUsernameLineEdit{border-radius:10px;padding-left:10px}")
        self.StudentUsernameLineEdit.setPlaceholderText("Username")
        self.StudentUsernameLineEdit.setObjectName("StudentUsernameLineEdit")
        self.StudentPasswordLineEdit = QtWidgets.QLineEdit(self.studentLoginPage)
        self.StudentPasswordLineEdit.setGeometry(QtCore.QRect(450, 400, 300, 50))
        self.StudentPasswordLineEdit.setFont(font)
        self.StudentPasswordLineEdit.setStyleSheet("QLineEdit#StudentPasswordLineEdit{border-radius:10px;padding-left:10px}")
        self.StudentPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.StudentPasswordLineEdit.setPlaceholderText("Password")
        self.StudentPasswordLineEdit.setObjectName("StudentPasswordLineEdit")
        self.WelcomeButton = QtWidgets.QPushButton(self.studentLoginPage, clicked= lambda: self.gotoStudent())
        self.WelcomeButton.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font.setPointSize(15)
        font.setBold(True)
        self.WelcomeButton.setFont(font)
        self.WelcomeButton.setStyleSheet("QPushButton#WelcomeButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:5px;}\n"
"QPushButton#WelcomeButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#WelcomeButton:pressed{background-color: rgb(170, 170, 170);}")
        self.WelcomeButton.setText("Back to Welcome Page")
        self.WelcomeButton.setObjectName("WelcomeButton")
        self.StuLoginErrorLabel = QtWidgets.QLabel(self.studentLoginPage)
        self.StuLoginErrorLabel.setGeometry(QtCore.QRect(425, 225, 350, 0))
        font.setPointSize(12)
        font.setBold(False)
        self.StuLoginErrorLabel.setFont(font)
        self.StuLoginErrorLabel.setStyleSheet("QLabel#StuLoginErrorLabel{padding-left: 10px;background-color: rgb(247,221,220);color: rgb(113, 43, 41)}")
        self.StuLoginErrorLabel.setText("Incorrect username or password")
        self.StuLoginErrorLabel.setObjectName("StuLoginErrorLabel")
        self.stackedWidget.addWidget(self.studentLoginPage)
#-----------------------------------------------------------------------Teacher Login Page
        self.teacherLoginPage = QtWidgets.QWidget()
        self.teacherLoginPage.setObjectName("teacherLoginPage")
        self.WelcomeButton_2 = QtWidgets.QPushButton(self.teacherLoginPage, clicked= lambda: self.gotoTeacher())
        self.WelcomeButton_2.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font.setBold(True)
        font.setPointSize(15)
        self.WelcomeButton_2.setFont(font)
        self.WelcomeButton_2.setStyleSheet("QPushButton#WelcomeButton_2{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:5px;}\n"
"QPushButton#WelcomeButton_2:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#WelcomeButton_2:pressed{background-color: rgb(170, 170, 170);}")
        self.WelcomeButton_2.setText("Back to Welcome Page")
        self.WelcomeButton_2.setObjectName("WelcomeButton_2")
        self.TeacherUsernameLineEdit = QtWidgets.QLineEdit(self.teacherLoginPage)
        self.TeacherUsernameLineEdit.setGeometry(QtCore.QRect(450, 300, 300, 50))
        font.setPointSize(15)
        font.setBold(False)
        self.TeacherUsernameLineEdit.setFont(font)
        self.TeacherUsernameLineEdit.setStyleSheet("QLineEdit#TeacherUsernameLineEdit{border-radius:10px;padding-left:10px}")
        self.TeacherUsernameLineEdit.setPlaceholderText("Username")
        self.TeacherUsernameLineEdit.setObjectName("TeacherUsernameLineEdit")
        self.TeacherPasswordLineEdit = QtWidgets.QLineEdit(self.teacherLoginPage)
        self.TeacherPasswordLineEdit.setGeometry(QtCore.QRect(450, 400, 300, 50))
        self.TeacherPasswordLineEdit.setFont(font)
        self.TeacherPasswordLineEdit.setStyleSheet("QLineEdit#TeacherPasswordLineEdit{border-radius:10px;padding-left:10px}")
        self.TeacherPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.TeacherPasswordLineEdit.setPlaceholderText("Password")
        self.TeacherPasswordLineEdit.setObjectName("TeacherPasswordLineEdit")
        self.TeacherLoginLabel = QtWidgets.QLabel(self.teacherLoginPage)
        self.TeacherLoginLabel.setGeometry(QtCore.QRect(400, 125, 400, 100))
        font.setPointSize(30)
        font.setBold(True)
        self.TeacherLoginLabel.setFont(font)
        self.TeacherLoginLabel.setStyleSheet("color: rgb(255, 255, 255);background-color:rgb(0,0,0);border-radius:10px;")
        self.TeacherLoginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TeacherLoginLabel.setText("Teacher Login")
        self.TeacherLoginLabel.setObjectName("TeacherLoginLabel")
        self.TeacherLoginButton = QtWidgets.QPushButton(self.teacherLoginPage, clicked= lambda: self.teacher_login())
        self.TeacherLoginButton.setGeometry(QtCore.QRect(450, 525, 300, 60))
        font.setPointSize(20)
        self.TeacherLoginButton.setFont(font)
        self.TeacherLoginButton.setStyleSheet("QPushButton#TeacherLoginButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#TeacherLoginButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#TeacherLoginButton:pressed{background-color: rgb(170, 170, 170);}")
        self.TeacherLoginButton.setText("Log In")
        self.TeacherLoginButton.setObjectName("TeacherLoginButton")
        self.TeaLoginErrorLabel = QtWidgets.QLabel(self.teacherLoginPage)
        self.TeaLoginErrorLabel.setGeometry(QtCore.QRect(425, 225, 350, 0))
        font.setPointSize(12)
        font.setBold(False)
        self.TeaLoginErrorLabel.setFont(font)
        self.TeaLoginErrorLabel.setStyleSheet("QLabel#TeaLoginErrorLabel{padding-left: 10px;background-color: rgb(247,221,220);color: rgb(113, 43, 41)}")
        self.TeaLoginErrorLabel.setText("Incorrect username or password")
        self.TeaLoginErrorLabel.setObjectName("TeaLoginErrorLabel")
        self.stackedWidget.addWidget(self.teacherLoginPage)
#-----------------------------------------------------------------------Student Register Page
        self.studentRegisterPage = QtWidgets.QWidget()
        self.studentRegisterPage.setObjectName("studentRegisterPage")
        self.StudentRegisterLabel = QtWidgets.QLabel(self.studentRegisterPage)
        self.StudentRegisterLabel.setGeometry(QtCore.QRect(375, 70, 450, 100))
        font.setPointSize(30)
        font.setBold(True)
        self.StudentRegisterLabel.setFont(font)
        self.StudentRegisterLabel.setStyleSheet("color: rgb(255, 255, 255);background-color:rgb(0,0,0);border-radius:10px;")
        self.StudentRegisterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StudentRegisterLabel.setText("Student Register")
        self.StudentRegisterLabel.setObjectName("StudentRegisterLabel")
        self.StuPasswordLabel = QtWidgets.QLabel(self.studentRegisterPage)
        self.StuPasswordLabel.setGeometry(QtCore.QRect(360, 540, 200, 50))
        font.setPointSize(20)
        self.StuPasswordLabel.setFont(font)
        self.StuPasswordLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.StuPasswordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StuPasswordLabel.setText("Password")
        self.StuPasswordLabel.setObjectName("StuPasswordLabel")
        self.StuUsernameLabel = QtWidgets.QLabel(self.studentRegisterPage)
        self.StuUsernameLabel.setGeometry(QtCore.QRect(360, 440, 200, 50))
        self.StuUsernameLabel.setFont(font)
        self.StuUsernameLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.StuUsernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StuUsernameLabel.setText("Username")
        self.StuUsernameLabel.setObjectName("StuUsernameLabel")
        self.StuFirstNameLabel = QtWidgets.QLabel(self.studentRegisterPage)
        self.StuFirstNameLabel.setGeometry(QtCore.QRect(360, 240, 200, 50))
        self.StuFirstNameLabel.setFont(font)
        self.StuFirstNameLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.StuFirstNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StuFirstNameLabel.setText("First Name")
        self.StuFirstNameLabel.setObjectName("StuFirstNameLabel")
        self.StuSurnameLabel = QtWidgets.QLabel(self.studentRegisterPage)
        self.StuSurnameLabel.setGeometry(QtCore.QRect(360, 340, 200, 50))
        self.StuSurnameLabel.setFont(font)
        self.StuSurnameLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.StuSurnameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StuSurnameLabel.setText("Surname")
        self.StuSurnameLabel.setObjectName("StuSurnameLabel")
        self.StudentRegisterButton = QtWidgets.QPushButton(self.studentRegisterPage, clicked= lambda: self.save_student())
        self.StudentRegisterButton.setGeometry(QtCore.QRect(450, 650, 300, 60))
        font.setPointSize(15)
        self.StudentRegisterButton.setFont(font)
        self.StudentRegisterButton.setStyleSheet("QPushButton#StudentRegisterButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#StudentRegisterButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#StudentRegisterButton:pressed{background-color: rgb(170, 170, 170);}")
        self.StudentRegisterButton.setText("Create Account")
        self.StudentRegisterButton.setObjectName("StudentRegisterButton")
        self.WelcomeButton_3 = QtWidgets.QPushButton(self.studentRegisterPage, clicked= lambda: self.gotoStudent())
        self.WelcomeButton_3.setGeometry(QtCore.QRect(0, 0, 300, 50))
        self.WelcomeButton_3.setFont(font)
        self.WelcomeButton_3.setStyleSheet("QPushButton#WelcomeButton_3{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:5px;}\n"
"QPushButton#WelcomeButton_3:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#WelcomeButton_3:pressed{background-color: rgb(170, 170, 170);}")
        self.WelcomeButton_3.setText("Back to Welcome Page")
        self.WelcomeButton_3.setObjectName("WelcomeButton_3")
        self.StuFNameLineEdit = QtWidgets.QLineEdit(self.studentRegisterPage)
        self.StuFNameLineEdit.setGeometry(QtCore.QRect(580, 240, 250, 50))
        font.setPointSize(15)
        font.setBold(False)
        self.StuFNameLineEdit.setFont(font)
        self.StuFNameLineEdit.setObjectName("StuFNameLineEdit")
        self.StuSurnameLineEdit = QtWidgets.QLineEdit(self.studentRegisterPage)
        self.StuSurnameLineEdit.setGeometry(QtCore.QRect(580, 340, 250, 50))
        self.StuSurnameLineEdit.setFont(font)
        self.StuSurnameLineEdit.setObjectName("StuSurnameLineEdit")
        self.StuUsernameLineEdit = QtWidgets.QLineEdit(self.studentRegisterPage)
        self.StuUsernameLineEdit.setGeometry(QtCore.QRect(580, 440, 250, 50))
        self.StuUsernameLineEdit.setFont(font)
        self.StuUsernameLineEdit.setObjectName("StuUsernameLineEdit")
        self.StuPasswordLineEdit = QtWidgets.QLineEdit(self.studentRegisterPage)
        self.StuPasswordLineEdit.setGeometry(QtCore.QRect(580, 540, 250, 50))
        self.StuPasswordLineEdit.setFont(font)
        self.StuPasswordLineEdit.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.StuPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.StuPasswordLineEdit.setObjectName("StuPasswordLineEdit")
        self.StuRegErrorLabel = QtWidgets.QLabel(self.studentRegisterPage)
        self.StuRegErrorLabel.setGeometry(QtCore.QRect(375, 170, 450, 0))
        font.setPointSize(11)
        self.StuRegErrorLabel.setFont(font)
        self.StuRegErrorLabel.setStyleSheet("QLabel#StuRegErrorLabel{padding-left: 10px;background-color: rgb(247,221,220);color: rgb(113, 43, 41)}")
        self.StuRegErrorLabel.setText("Username already exists, Please try again or Login.")
        self.StuRegErrorLabel.setObjectName("StuRegErrorLabel")
        self.stackedWidget.addWidget(self.studentRegisterPage)
#-----------------------------------------------------------------------Teacher Register Page
        self.teacherRegisterPage = QtWidgets.QWidget()
        self.teacherRegisterPage.setObjectName("teacherRegisterPage")
        self.TeacherRegisterLabel = QtWidgets.QLabel(self.teacherRegisterPage)
        self.TeacherRegisterLabel.setGeometry(QtCore.QRect(375, 20, 450, 100))
        font.setPointSize(30)
        font.setBold(True)
        self.TeacherRegisterLabel.setFont(font)
        self.TeacherRegisterLabel.setStyleSheet("color: rgb(255, 255, 255);background-color:rgb(0,0,0);border-radius:10px;")
        self.TeacherRegisterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TeacherRegisterLabel.setText("Teacher Register")
        self.TeacherRegisterLabel.setObjectName("TeacherRegisterLabel")
        self.TeaFNameLabel = QtWidgets.QLabel(self.teacherRegisterPage)
        self.TeaFNameLabel.setGeometry(QtCore.QRect(370, 280, 200, 50))
        font.setPointSize(20)
        self.TeaFNameLabel.setFont(font)
        self.TeaFNameLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.TeaFNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TeaFNameLabel.setText("First Name")
        self.TeaFNameLabel.setObjectName("TeaFNameLabel")
        self.TitleLabel = QtWidgets.QLabel(self.teacherRegisterPage)
        self.TitleLabel.setGeometry(QtCore.QRect(370, 200, 200, 50))
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setText("Title")
        self.TitleLabel.setObjectName("TitleLabel")
        self.TeaSurnameLabel = QtWidgets.QLabel(self.teacherRegisterPage)
        self.TeaSurnameLabel.setGeometry(QtCore.QRect(370, 370, 200, 50))
        self.TeaSurnameLabel.setFont(font)
        self.TeaSurnameLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.TeaSurnameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TeaSurnameLabel.setText("Surname")
        self.TeaSurnameLabel.setObjectName("TeaSurnameLabel")
        self.TeaUsernameLabel = QtWidgets.QLabel(self.teacherRegisterPage)
        self.TeaUsernameLabel.setGeometry(QtCore.QRect(370, 460, 200, 50))
        self.TeaUsernameLabel.setFont(font)
        self.TeaUsernameLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.TeaUsernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TeaUsernameLabel.setText("Username")
        self.TeaUsernameLabel.setObjectName("TeaUsernameLabel")
        self.TeaPasswordLabel = QtWidgets.QLabel(self.teacherRegisterPage)
        self.TeaPasswordLabel.setGeometry(QtCore.QRect(370, 550, 200, 50))
        self.TeaPasswordLabel.setFont(font)
        self.TeaPasswordLabel.setStyleSheet("color: rgb(170, 170, 170);background-color:rgb(0,0,0);border-radius:10px;")
        self.TeaPasswordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TeaPasswordLabel.setText("Password")
        self.TeaPasswordLabel.setObjectName("TeaPasswordLabel")
        self.TeacherRegisterButton = QtWidgets.QPushButton(self.teacherRegisterPage, clicked =lambda: self.save_teacher())
        self.TeacherRegisterButton.setGeometry(QtCore.QRect(450, 670, 300, 60))
        font.setPointSize(15)
        self.TeacherRegisterButton.setFont(font)
        self.TeacherRegisterButton.setStyleSheet("QPushButton#TeacherRegisterButton{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:10px;}\n"
"QPushButton#TeacherRegisterButton:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#TeacherRegisterButton:pressed{background-color: rgb(170, 170, 170);}")
        self.TeacherRegisterButton.setText("Create Account")
        self.TeacherRegisterButton.setObjectName("TeacherRegisterButton")
        self.WelcomeButton_4 = QtWidgets.QPushButton(self.teacherRegisterPage, clicked= lambda: self.gotoTeacher())
        self.WelcomeButton_4.setGeometry(QtCore.QRect(0, 0, 300, 50))
        self.WelcomeButton_4.setFont(font)
        self.WelcomeButton_4.setStyleSheet("QPushButton#WelcomeButton_4{background-color: rgb(24, 24, 24);color: rgb(255, 255, 255);border-radius:5px;}\n"
"QPushButton#WelcomeButton_4:hover{background-color: rgb(61, 61, 61);}\n"
"QPushButton#WelcomeButton_4:pressed{background-color: rgb(170, 170, 170);}")
        self.WelcomeButton_4.setText("Back to Welcome Page")
        self.WelcomeButton_4.setObjectName("WelcomeButton_4")
        self.TitleComboBox = QtWidgets.QComboBox(self.teacherRegisterPage)
        self.TitleComboBox.setGeometry(QtCore.QRect(630, 210, 100, 35))
        self.TitleComboBox.setObjectName("TitleComboBox")
        font.setPointSize(15)
        font.setBold(False)
        self.TitleComboBox.setFont(font)
        titles = ["Mr","Mrs","Miss","Ms","Dr"]
        self.TitleComboBox.addItems(titles)
        self.TeaFNameLineEdit = QtWidgets.QLineEdit(self.teacherRegisterPage)
        self.TeaFNameLineEdit.setGeometry(QtCore.QRect(630, 280, 250, 50))
        self.TeaFNameLineEdit.setFont(font)
        self.TeaFNameLineEdit.setObjectName("TeaFNameLineEdit")
        self.TeaSurnameLineEdit = QtWidgets.QLineEdit(self.teacherRegisterPage)
        self.TeaSurnameLineEdit.setGeometry(QtCore.QRect(630, 370, 250, 50))
        self.TeaSurnameLineEdit.setFont(font)
        self.TeaSurnameLineEdit.setObjectName("TeaSurnameLineEdit")
        self.TeaUsernameLineEdit = QtWidgets.QLineEdit(self.teacherRegisterPage)
        self.TeaUsernameLineEdit.setGeometry(QtCore.QRect(630, 460, 250, 50))
        self.TeaUsernameLineEdit.setFont(font)
        self.TeaUsernameLineEdit.setObjectName("TeaUsernameLineEdit")
        self.TeaPasswordLineEdit = QtWidgets.QLineEdit(self.teacherRegisterPage)
        self.TeaPasswordLineEdit.setGeometry(QtCore.QRect(630, 550, 250, 50))
        self.TeaPasswordLineEdit.setFont(font)
        self.TeaPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.TeaPasswordLineEdit.setObjectName("TeaPasswordLineEdit")
        self.TeaRegErrorLabel = QtWidgets.QLabel(self.teacherRegisterPage)
        self.TeaRegErrorLabel.setGeometry(QtCore.QRect(370, 130, 500, 0))
        font.setPointSize(11)
        self.TeaRegErrorLabel.setFont(font)
        self.TeaRegErrorLabel.setStyleSheet("QLabel#TeaRegErrorLabel{padding-left: 10px;background-color: rgb(247,221,220);color: rgb(113, 43, 41)}")
        self.TeaRegErrorLabel.setObjectName("TeaRegErrorLabel")
        self.stackedWidget.addWidget(self.teacherRegisterPage)
        WelcomePage.setCentralWidget(self.centralwidget)
        self.stackedWidget.setCurrentIndex(1)

    def openStudentMainPage(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_StudentMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openTeacherMainPage(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TeacherMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

# Visits the corresponding pages when the functions are called:
    def gotoTeacher(self):
        ui.stackedWidget.setCurrentIndex(0)
    def gotoStudent(self):
        ui.stackedWidget.setCurrentIndex(1)
    def gotoStudentLoginPage(self):
        ui.stackedWidget.setCurrentIndex(2)
    def gotoTeacherLoginPage(self):
        ui.stackedWidget.setCurrentIndex(3)
    def gotoStudentRegisterPage(self):
        ui.stackedWidget.setCurrentIndex(4)
    def gotoTeacherRegisterPage(self):
        ui.stackedWidget.setCurrentIndex(5)
# Saves the Student's register details to the database
    def save_student(self):
        connection = sqlite3.connect("Users.db")
        cursor = connection.cursor()
        first_name = self.StuFNameLineEdit.text()
        surname = self.StuSurnameLineEdit.text()
        username = self.StuUsernameLineEdit.text()
        password = self.StuPasswordLineEdit.text()
        Logged_in = 1
        if first_name != "" and surname != "" and username != "" and password != "":
            if len(password) < 8:
                self.StuRegErrorLabel.setText("Password must be at least 8 characters long.")
                self.StuRegErrorLabel.setFixedHeight(50)
            else:
                statement = f"SELECT username FROM tblStudentUsers WHERE username='{username}';"
                cursor.execute(statement)
                if not cursor.fetchone():
                    sqlCommand = "INSERT INTO tblStudentUsers (firstName,surname,username,password,Logged_in) VALUES (?,?,?,?,?);"
                    record = (first_name,surname,username,password,Logged_in)
                    cursor.execute(sqlCommand,record)
                    cursor.execute(f"UPDATE tblStudentUsers SET Logged_in='{0}' WHERE username!='{username}';")
                    connection.commit()
                    connection.close()
                    self.openStudentMainPage()
                else:
                    self.StuRegErrorLabel.setText("Username already exists, Please try again or Login.")
                    self.StuRegErrorLabel.setFixedHeight(50)
        else:
            self.StuRegErrorLabel.setText("Fields are incomplete. Please fill all the boxes.")
            self.StuRegErrorLabel.setFixedHeight(50)

# Saves the Teacher's register details to the database
    def save_teacher(self):
        connection = sqlite3.connect("Users.db")
        cursor = connection.cursor()
        title = self.TitleComboBox.currentText()
        first_name = self.TeaFNameLineEdit.text()
        surname = self.TeaSurnameLineEdit.text()
        username = self.TeaUsernameLineEdit.text()
        password = self.TeaPasswordLineEdit.text()
        Logged_in = 1
        if first_name != "" and surname != "" and username != "" and password != "":
            if len(password) < 8:
                self.TeaRegErrorLabel.setText("Password must be at least 8 characters long.")
                self.TeaRegErrorLabel.setFixedHeight(50)
            else:
                statement = f"SELECT username FROM tblTeacherUsers WHERE username='{username}';"
                cursor.execute(statement)
                if not cursor.fetchone():
                    sqlCommand = "INSERT INTO tblTeacherUsers (title,firstName,surname,username,password,Logged_in) VALUES (?,?,?,?,?,?);"
                    record = (title,first_name,surname,username,password,Logged_in)
                    cursor.execute(sqlCommand,record)
                    cursor.execute(f"UPDATE tblTeacherUsers SET Logged_in='{0}' WHERE username!='{username}';")
                    connection.commit()
                    connection.close()
                    self.openTeacherMainPage()
                else:
                    self.TeaRegErrorLabel.setText("Username already exists, Please try again or Login.")
                    self.TeaRegErrorLabel.setFixedHeight(50)
        else:
            self.TeaRegErrorLabel.setText("Fields are incomplete. Please fill all the boxes.")
            self.TeaRegErrorLabel.setFixedHeight(50)

# Checks if login details are correct
    def student_login(self):
        username = self.StudentUsernameLineEdit.text()
        password = self.StudentPasswordLineEdit.text()
        connection = sqlite3.connect("Users.db")
        cur = connection.cursor()
        statement = f"SELECT username FROM tblStudentUsers WHERE username='{username}' AND password='{password}';"
        cur.execute(statement)
        if not cur.fetchone():
            self.StuLoginErrorLabel.setFixedHeight(50)
        else:
            cur.execute(f"UPDATE tblStudentUsers SET Logged_in='{1}' WHERE username='{username}';")
            cur.execute(f"UPDATE tblStudentUsers SET Logged_in='{0}' WHERE username!='{username}';")
            connection.commit()
            connection.close()
            self.openStudentMainPage()

    def teacher_login(self):
        username = self.TeacherUsernameLineEdit.text()
        password = self.TeacherPasswordLineEdit.text()
        connection = sqlite3.connect("Users.db")
        cur = connection.cursor()
        statement = f"SELECT username FROM tblTeacherUsers WHERE username='{username}' AND password='{password}';"
        cur.execute(statement)
        if not cur.fetchone():  # An empty result evaluates to False.
            self.TeaLoginErrorLabel.setFixedHeight(50)
        else:
            cur.execute(f"UPDATE tblTeacherUsers SET Logged_in='{1}' WHERE username='{username}';")
            cur.execute(f"UPDATE tblTeacherUsers SET Logged_in='{0}' WHERE username!='{username}';")
            connection.commit()
            connection.close()
            self.openTeacherMainPage()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomePage = QtWidgets.QMainWindow()
    ui = Ui_WelcomePage()
    ui.setupUi(WelcomePage)
    WelcomePage.show()
    sys.exit(app.exec_())